## Exercice 1.1 — Premiers pas avec ndarray
Objectif : Comprendre ce qu'est un **ndarray** et comment le créer. Instructions :

- Importez NumPy sous l'alias **np**.
- Créez un tableau NumPy à partir de la colonne **Age** d'**employee_satisfaction.csv**.
- Créez un second tableau à partir d'une simple liste Python de votre choix.
- Comparez les deux objets : type, comportement, opérations possibles. <br>
**Difficulté** : 🟢 Débutant

In [74]:
# Import de Numpy as np
import numpy as np
import pandas as pd
import time

# Lecture du fichier
employes = pd.read_csv('../datasets/employee_satisfaction.csv')
employes = employes.dropna()
# Creation d'un tableau Numpy a partir de la colonne Age
tableau_age = np.array(employes['Age'])

# Liste python de choix
liste_notes = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# Creation d'un tableau a partir d'une liste 
tableau_notes = np.array(liste_notes)

tableau_notes.shape
employes

,ID_Employe,Age,Sexe,Departement,Annees_Experience,Niveau_Etudes,Salaire_Mensuel_BIF,Travail_A_Distance,Heures_Supplementaires,Heures_Formation,Anciennete_Entreprise,Nombre_Promotions,Evaluation_Performance,Equilibre_Vie_Travail,Satisfaction_Salaire,Nombre_Absences,Satisfait
0,1,58.0,Homme,Marketing,12.0,Licence,2804177.0,Oui,13.0,95.0,8.0,0.0,3.0,Bon,Insatisfait,16.0,Oui
3,4,27.0,Femme,Production,3.0,Licence,896874.0,Non,14.0,109.0,2.0,0.0,5.0,Moyen,Très insatisfait,16.0,Non
5,6,58.0,Femme,Production,18.0,Licence,2658571.0,Non,34.0,91.0,11.0,2.0,2.0,Très mauvais,Insatisfait,30.0,Non
7,8,42.0,Homme,Commercial,8.0,Secondaire,1635366.0,Non,34.0,104.0,4.0,1.0,5.0,Moyen,Satisfait,17.0,Oui
8,9,30.0,Homme,Commercial,6.0,Licence,1890079.0,Oui,18.0,86.0,1.0,1.0,3.0,Bon,Insatisfait,26.0,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,44.0,Homme,Marketing,7.0,Secondaire,1488252.0,Oui,3.0,40.0,0.0,0.0,5.0,Moyen,Neutre,7.0,Oui
501,502,40.0,Homme,Logistique,18.0,Licence,3273162.0,Oui,39.0,0.0,16.0,4.0,4.0,Moyen,Neutre,24.0,Non
503,504,49.0,Homme,Logistique,14.0,Master,3501730.0,Non,1.0,98.0,9.0,0.0,3.0,Bon,Très insatisfait,24.0,Non
506,507,23.0,Homme,Informatique,0.0,Licence,579742.0,Non,21.0,81.0,0.0,1.0,4.0,Mauvais,Satisfait,5.0,Oui


## Exercice 1.2 — Comprendre les dimensions (**shape**)
Objectif : Maîtriser la notion de dimensions d'un tableau. Instructions :

- Construisez un tableau 2D à partir de trois colonnes numériques du dataset employés (par exemple **Age**, **Annees_Experience**, **Salaire_Mensuel_BIF**).
- Affichez *shape*, *ndim* et *size* de ce tableau.
- Expliquez en une phrase la différence entre shape et size.<br>
**Difficulté** : 🟢 Débutant

In [75]:
# Construction d'un tableau 2D a partir des 3 colonnes du dataset
matrice_2d = employes[["Age", "Annees_Experience", "Salaire_Mensuel_BIF"]]

# Affichage de shape, ndim et size
print("Shape: ", matrice_2d.shape)
print("Dimensions: ", matrice_2d.ndim)
print("Taille: ", matrice_2d.size)

# La difference entre shape et size reside au niveau de la valeur retourne

Shape:  (238, 3)
Dimensions:  2
Taille:  714


## Exercice 1.3 — Comprendre les types (dtype)
Objectif : Comprendre comment NumPy gère les types de données. 

Instructions :

- Affichez le **dtype** d'un tableau construit à partir de **Salaire_Mensuel_BIF** puis d'un tableau construit à partir de **ID_Employe**.
- Convertissez un tableau de flottants en entiers avec astype.
- Expliquez pourquoi cette conversion peut faire perdre de l'information.<br> 
**Difficulté** : 🟢 Débutant

In [76]:
# Extraction de Salaire_Mesnsuel_BIF
salaire_mensuel = employes["Salaire_Mensuel_BIF"]

# Construction du tableau
tableau_salaire_mensuel = np.array(salaire_mensuel)

# Affichage de dtype du tableau
tableau_salaire_mensuel.dtype

dtype('float64')

In [77]:
# Extraction de ID_Employe
id_employe = employes["ID_Employe"]

# Construction du tableau
tableau_id_employe = np.array(id_employe)

# Affichage de dtype du tableau
tableau_id_employe.dtype

dtype('int64')

In [78]:
# Conversion du tableau de flottants en entier
tableau_salaire_mensuel.astype('int')

array([2804177,  896874, 2658571, 1635366, 1890079, 2414085, 6000000,
       4945462, 1157946, 2721797, 1005815, 4505087, 2081193, 4947611,
       2803784, 1244979, 2871628,  393434, 1438257, 2510329,  963979,
       2990105,  783169,  970891, 1076223, 5168567, 1165604,  519448,
        918336, 3369738, 2345027,  962412, 1066341, 1629767, 1265788,
       2085536, 1557311, 1023963, 3296199, 5451154, 1566815, 1299653,
       1012407,  593670, 3705437, 1779815,  329568, 1786805, 5300668,
       6000000, 1171667,  809365, 3358859,  395576, 4789735, 1178288,
       1976461, 1515528,  994628, 5400227,  841933, 3184705, 1491327,
       3816120, 6000000, 6000000, 2104638, 2174180, 6000000, 1486826,
        973578,  300558, 1734020, 4637163, 4632481, 3799363, 3172735,
       3379506,  562320,  319192, 1499660, 4912946, 6000000, 6000000,
        724088,  728248, 3618160,  584341, 1315664, 4255585,  507324,
       1153031,  742333, 1788419,  467734,  732141, 1395516,  795727,
       3581208,  458

## Exercice 1.4 — Indexation
Objectif : Accéder à des éléments précis d'un tableau. 

Instructions :

- À partir d'un tableau des salaires, affichez le salaire du 1er, du 10ᵉ et du dernier employé.
- Modifiez la valeur d'un élément précis du tableau.
- Récupérez plusieurs éléments non consécutifs en une seule instruction (indexation par liste d'indices). <br>
**Difficulté** : 🟢 Débutant

In [79]:
salaires = np.array(salaire_mensuel)
# Salaire du 1er employé
premier = salaires[0]

# Salaire du 10e employé
dixieme = salaires[9]

# Salaire du dernier employé
dernier = salaires[-1]

print("1er salaire :", premier)
print("10e salaire :", dixieme)
print("Dernier salaire :", dernier)

1er salaire : 2804177.0
10e salaire : 2721797.0
Dernier salaire : 1426015.0


In [80]:
# Modifier le salaire du 3e employé
salaires[2] = 850000
print(salaires)

[2804177.  896874.  850000. 1635366. 1890079. 2414085. 6000000. 4945462.
 1157946. 2721797. 1005815. 4505087. 2081193. 4947611. 2803784. 1244979.
 2871628.  393434. 1438257. 2510329.  963979. 2990105.  783169.  970891.
 1076223. 5168567. 1165604.  519448.  918336. 3369738. 2345027.  962412.
 1066341. 1629767. 1265788. 2085536. 1557311. 1023963. 3296199. 5451154.
 1566815. 1299653. 1012407.  593670. 3705437. 1779815.  329568. 1786805.
 5300668. 6000000. 1171667.  809365. 3358859.  395576. 4789735. 1178288.
 1976461. 1515528.  994628. 5400227.  841933. 3184705. 1491327. 3816120.
 6000000. 6000000. 2104638. 2174180. 6000000. 1486826.  973578.  300558.
 1734020. 4637163. 4632481. 3799363. 3172735. 3379506.  562320.  319192.
 1499660. 4912946. 6000000. 6000000.  724088.  728248. 3618160.  584341.
 1315664. 4255585.  507324. 1153031.  742333. 1788419.  467734.  732141.
 1395516.  795727. 3581208.  458445. 2454394. 5013803. 4190692. 3853464.
  510799. 3389712.  636294. 1619713. 3331971. 22118

In [81]:
# Récupérer les salaires des employés 1, 5 et 10
indices = [0, 4, 9]
selection = salaires[indices]
print(selection)

[2804177. 1890079. 2721797.]


## Exercice 1.5 — Slicing
Objectif : Extraire des sous-ensembles de tableaux. 

Instructions :

- Extrayez les 20 premiers âges, puis les 20 derniers.
- Extrayez un élément sur deux (pas de 2) dans le tableau des salaires.
- Inversez complètement un tableau à l'aide du slicing. <br>
***Difficulté*** : 🟢 Débutant

In [82]:
# Recuperation des ages dans le dataset
ages = np.array(employes["Age"])

# Affichage des 20 premiers ages
ages[:20]

array([58., 27., 58., 42., 30., 30., 21., 43., 21., 43., 21., 40., 41.,
       46., 47., 35., 34., 22., 56., 58.])

In [83]:
# Extraction des elements avec pas de 2
salaires[::2]

array([2804177.,  850000., 1890079., 6000000., 1157946., 1005815.,
       2081193., 2803784., 2871628., 1438257.,  963979.,  783169.,
       1076223., 1165604.,  918336., 2345027., 1066341., 1265788.,
       1557311., 3296199., 1566815., 1012407., 3705437.,  329568.,
       5300668., 1171667., 3358859., 4789735., 1976461.,  994628.,
        841933., 1491327., 6000000., 2104638., 6000000.,  973578.,
       1734020., 4632481., 3172735.,  562320., 1499660., 6000000.,
        724088., 3618160., 1315664.,  507324.,  742333.,  467734.,
       1395516., 3581208., 2454394., 4190692.,  510799.,  636294.,
       3331971., 4895489.,  597900., 3265874., 2575213., 1717534.,
       2759211.,  826379., 5221147., 4958707.,  788216., 1485299.,
       5847838., 3787973., 4055884., 3348401., 4325904., 4998784.,
       2768007., 3231137., 2696021., 3229409.,  800316., 5122328.,
       1426015., 2297733.,  990961., 1062853., 1194233., 1987587.,
        868297., 4093382., 1140178., 3374422., 6000000.,  9942

In [84]:
# Inversion complete avec le slicing
salaires[::-1]

array([1426015.,  579742., 3501730., 3273162., 1488252., 5933987.,
       1743751.,  848364., 1187658., 3918462., 4572226.,  408117.,
        783608., 2268093., 3336476.,  446664., 4459058., 4230866.,
        574071., 1474434., 1556288., 2143712.,  926445.,  547333.,
        810863., 2420517., 5416134.,  457020., 1480618., 2131324.,
        868046., 6000000.,  780237., 3175014.,  487927., 2229447.,
       1097366.,  405712., 3150036.,  647712., 1224436., 2647823.,
        853353.,  487797., 6000000., 2586686.,  567577., 3501730.,
        660350., 5486713., 1517672.,  624547., 1192667.,  954610.,
        960627.,  606025.,  546102., 5666040., 1085744.,  994267.,
       1206007., 6000000., 4451837., 3374422., 1901902., 1140178.,
       1197763., 4093382., 5134904.,  868297., 1743147., 1987587.,
       2042024., 1194233., 2785038., 1062853., 2052240.,  990961.,
       5385040., 2297733., 4686563., 1426015., 6000000., 5122328.,
       2504762.,  800316., 5277013., 3229409.,  801555., 26960

## Exercice 1.6 — Indexation booléenne
Objectif : Filtrer un tableau selon une condition logique. 

Instructions :

- Créez un masque booléen identifiant les employés de plus de 50 ans.
- Utilisez ce masque pour extraire leurs salaires.
- Comptez combien d'employés ont plus de 20 absences (Nombre_Absences).
- Combinez deux conditions (ex. âge > 40 et ancienneté > 5) avec les opérateurs & et |. <br>
**Difficulté** : 🟡 Intermédiaire

In [85]:
# Création du masque
masque_age = employes["Age"] > 50
print(masque_age)

0       True
3      False
5       True
7      False
8      False
       ...  
498    False
501    False
503    False
506    False
508    False
Name: Age, Length: 238, dtype: bool


In [86]:
# Salaires des employés de plus de 50 ans
salaires_plus_50 = employes.loc[
    masque_age,
    "Salaire_Mensuel_BIF"
]

print(salaires_plus_50)

0      2804177.0
5      2658571.0
31     1438257.0
35     2510329.0
50     1076223.0
51     5168567.0
61      962412.0
75     5451154.0
89     1786805.0
93     5300668.0
105    3358859.0
109    1178288.0
111    1976461.0
128    6000000.0
133    6000000.0
136    6000000.0
151    3379506.0
156    1499660.0
158    4912946.0
163    6000000.0
167     724088.0
170     728248.0
183    4255585.0
219    3581208.0
238    1619713.0
239    3331971.0
242    4895489.0
248    3265874.0
258    1514207.0
267    4076072.0
270    4958707.0
278    1583042.0
288    3787973.0
293    3348401.0
304    2768007.0
322    3229409.0
330    6000000.0
333    4686563.0
336    5385040.0
353     868297.0
362    4093382.0
368    3374422.0
371    4451837.0
390     954610.0
414    6000000.0
418     853353.0
422    1224436.0
427    3150036.0
436    3175014.0
442    6000000.0
443     868046.0
444    2131324.0
448    5416134.0
449    2420517.0
466    4459058.0
487     408117.0
488    4572226.0
493    1187658.0
Name: Salaire_

In [87]:
# Employés ayant plus de 20 absences
nombre_absences = (employes["Nombre_Absences"] > 20).sum()

print(
    "Nombre d'employés avec plus de 20 absences :",
    nombre_absences
)

Nombre d'employés avec plus de 20 absences : 77


In [88]:
employes_experimentes = employes[
    (employes["Age"] > 40) &
    (employes["Anciennete_Entreprise"] > 5)
]

print(employes_experimentes)

     ID_Employe   Age   Sexe                 Departement  Annees_Experience  \
0             1  58.0  Homme                   Marketing               12.0   
5             6  58.0  Femme                  Production               18.0   
13           14  43.0  Femme              Support Client               25.0   
24           25  41.0  Femme                     Finance                6.0   
26           27  46.0  Femme              Administration               20.0   
27           28  47.0  Femme                Informatique                9.0   
44           45  47.0  Femme                  Production                6.0   
51           52  59.0  Femme         Ressources Humaines               28.0   
75           76  60.0  Homme  Recherche et Développement               27.0   
93           94  58.0  Femme         Ressources Humaines               20.0   
95           96  47.0  Femme         Ressources Humaines               27.0   
108         109  46.0  Femme                Informat

In [89]:
employes_age_ou_anciens = employes[
    (employes["Age"] > 40) |
    (employes["Anciennete_Entreprise"] > 5)
]

print(employes_age_ou_anciens)

     ID_Employe   Age   Sexe     Departement  Annees_Experience Niveau_Etudes  \
0             1  58.0  Homme       Marketing               12.0       Licence   
5             6  58.0  Femme      Production               18.0       Licence   
7             8  42.0  Homme      Commercial                8.0    Secondaire   
12           13  21.0  Femme    Informatique               35.0       Licence   
13           14  43.0  Femme  Support Client               25.0        Master   
..          ...   ...    ...             ...                ...           ...   
495         496  49.0  Femme    Informatique                2.0    Secondaire   
497         498  39.0  Homme      Commercial               18.0      Doctorat   
498         499  44.0  Homme       Marketing                7.0    Secondaire   
501         502  40.0  Homme      Logistique               18.0       Licence   
503         504  49.0  Homme      Logistique               14.0        Master   

     Salaire_Mensuel_BIF Tr

## Exercice 1.7 — Vectorisation
Objectif : Comprendre pourquoi NumPy est plus rapide qu'une boucle Python. 

Instructions :

- Convertissez le tableau des salaires (en BIF) en une nouvelle unité de votre choix, sans écrire de boucle for.
- Écrivez la même opération avec une boucle for classique.
- Comparez le temps d'exécution des deux approches avec le module time. <br>
**Difficulté** : 🟡 Intermédiaire

In [90]:
# Conversion BIF vers CAD
taux_conversion = 5500
salaires_cad = salaires / taux_conversion
print(salaires_cad)

[ 509.85036364  163.068       154.54545455  297.33927273  343.65072727
  438.92454545 1090.90909091  899.17490909  210.53563636  494.87218182
  182.87545455  819.10672727  378.39872727  899.56563636  509.77890909
  226.35981818  522.11418182   71.53345455  261.50127273  456.42345455
  175.26890909  543.65545455  142.39436364  176.52563636  195.67690909
  939.73945455  211.928        94.44509091  166.97018182  612.67963636
  426.36854545  174.984       193.88018182  296.32127273  230.14327273
  379.18836364  283.14745455  186.17509091  599.30890909  991.11890909
  284.87545455  236.30054545  184.074       107.94        673.71581818
  323.60272727   59.92145455  324.87363636  963.75781818 1090.90909091
  213.03036364  147.15727273  610.70163636   71.92290909  870.86090909
  214.23418182  359.35654545  275.55054545  180.84145455  981.85945455
  153.07872727  579.03727273  271.15036364  693.84       1090.90909091
 1090.90909091  382.66145455  395.30545455 1090.90909091  270.332
  177.01418

In [91]:
# Caonversion avec une boucle for
salaires_cad_for = []

for salaire in salaires:
    salaire_converti = salaire / taux_conversion
    salaires_cad_for.append(salaire_converti)

salaires_cad_for

[509.8503636363636,
 163.068,
 154.54545454545453,
 297.3392727272727,
 343.6507272727273,
 438.92454545454547,
 1090.909090909091,
 899.1749090909091,
 210.53563636363637,
 494.87218181818184,
 182.87545454545455,
 819.1067272727273,
 378.3987272727273,
 899.5656363636364,
 509.7789090909091,
 226.35981818181818,
 522.1141818181818,
 71.53345454545455,
 261.50127272727275,
 456.42345454545455,
 175.2689090909091,
 543.6554545454545,
 142.39436363636364,
 176.52563636363635,
 195.67690909090908,
 939.7394545454546,
 211.928,
 94.44509090909091,
 166.97018181818183,
 612.6796363636364,
 426.3685454545454,
 174.984,
 193.88018181818182,
 296.32127272727274,
 230.14327272727272,
 379.18836363636365,
 283.14745454545454,
 186.1750909090909,
 599.3089090909091,
 991.1189090909091,
 284.87545454545455,
 236.30054545454544,
 184.074,
 107.94,
 673.7158181818182,
 323.6027272727273,
 59.921454545454544,
 324.87363636363636,
 963.7578181818182,
 1090.909090909091,
 213.03036363636363,
 147.1572

In [103]:
# Temps d'execution sans boucle
debut = time.time()
salaires_usd_vectorise = salaires / taux_conversion
fin = time.time()
temps_numpy = fin - debut
print("Temps NumPy :", temps_numpy, "secondes")

Temps NumPy : 0.00013709068298339844 secondes


In [104]:
# Temps d'execution avec boucle
debut = time.time()
salaires_cad_for = []
for salaire in salaires:
    salaire_converti = salaire / taux_conversion
    salaires_cad_for.append(salaire_converti)
fin = time.time()
temps_numpy_for = fin - debut
print("Temps NumPy :", temps_numpy_for, "secondes")

Temps NumPy : 0.0005314350128173828 secondes


In [105]:
difference = temps_numpy_for / temps_numpy
print(
    f"La boucle for est environ {difference:.5f} fois plus lente"
)

La boucle for est environ 3.87652 fois plus lente


## Exercice 1.8 — Broadcasting
Objectif : Comprendre comment NumPy applique des opérations entre tableaux de formes différentes. 

Instructions :

- Appliquez une augmentation de salaire uniforme (par exemple +10 %) à tout le tableau des salaires en une seule opération.
- Centrez-réduisez (standardisez) un tableau numérique de votre choix en soustrayant sa moyenne puis en divisant par son écart-type.
- Expliquez ce que le broadcasting a permis d'éviter. <br>
**Difficulté** : 🟡 Intermédiaire

In [95]:
 #Augmentation de 10 %
salaires_augmentes = salaires * 1.10
salaires_augmentes

array([3084594.7,  986561.4,  935000. , 1798902.6, 2079086.9, 2655493.5,
       6600000. , 5440008.2, 1273740.6, 2993976.7, 1106396.5, 4955595.7,
       2289312.3, 5442372.1, 3084162.4, 1369476.9, 3158790.8,  432777.4,
       1582082.7, 2761361.9, 1060376.9, 3289115.5,  861485.9, 1067980.1,
       1183845.3, 5685423.7, 1282164.4,  571392.8, 1010169.6, 3706711.8,
       2579529.7, 1058653.2, 1172975.1, 1792743.7, 1392366.8, 2294089.6,
       1713042.1, 1126359.3, 3625818.9, 5996269.4, 1723496.5, 1429618.3,
       1113647.7,  653037. , 4075980.7, 1957796.5,  362524.8, 1965485.5,
       5830734.8, 6600000. , 1288833.7,  890301.5, 3694744.9,  435133.6,
       5268708.5, 1296116.8, 2174107.1, 1667080.8, 1094090.8, 5940249.7,
        926126.3, 3503175.5, 1640459.7, 4197732. , 6600000. , 6600000. ,
       2315101.8, 2391598. , 6600000. , 1635508.6, 1070935.8,  330613.8,
       1907422. , 5100879.3, 5095729.1, 4179299.3, 3490008.5, 3717456.6,
        618552. ,  351111.2, 1649626. , 5404240.6, 

In [96]:
# Calcul de la moyenne
moyenne = salaires.mean()

# Calcul de l'écart-type
ecart_type = salaires.std()

# Standardisation
salaires_standardises = (salaires - moyenne) / ecart_type

salaires_standardises

array([ 0.23992117, -0.86814615, -0.89537808, -0.43911162, -0.29113348,
        0.0132932 ,  2.09656745,  1.48392274, -0.71647368,  0.19206166,
       -0.80485575,  1.22808235, -0.18010383,  1.48517122,  0.23969285,
       -0.66591097,  0.27910752, -1.1606248 , -0.55362412,  0.06920715,
       -0.82916081,  0.34793795, -0.93420424, -0.82514521, -0.7639515 ,
        1.61353789, -0.71202469, -1.08741567, -0.85567758,  0.56848966,
       -0.02682675, -0.83007117, -0.76969255, -0.44236441, -0.65382176,
       -0.17758072, -0.48445847, -0.79431249,  0.52576642,  1.77770971,
       -0.47893703, -0.63414754, -0.80102606, -1.04429564,  0.76351745,
       -0.35519248, -1.19772841, -0.35113157,  1.69028332,  2.09656745,
       -0.70850233, -0.91898541,  0.56216939, -1.15938039,  1.39345154,
       -0.70465579, -0.24094897, -0.50873274, -0.81135496,  1.74812315,
       -0.90006469,  0.46099283, -0.52279256,  0.82781988,  2.09656745,
        2.09656745, -0.16648322, -0.12608208,  2.09656745, -0.52

Le broadcasting a permis d'éviter :

- l'écriture de boucles for explicites ;
- la création de tableaux intermédiaires contenant la même valeur répétée ;
- un code plus long et moins lisible ;
- une perte de performance liée aux boucles Python.

## Exercice 1.9 — Reshape
Objectif : Réorganiser la forme d'un tableau sans changer ses données. Instructions :

- Créez un tableau 1D de 12 valeurs (réelles ou générées) et transformez-le en matrice 3×4 puis en 4×3.
- Testez ce qu'il se passe si vous tentez un reshape avec un nombre d'éléments incompatible.
- Utilisez -1 dans un reshape et expliquez son rôle.<br> 
**Difficulté** : 🟡 Intermédiaire

In [108]:
# Création d'un tableau 1D de 12 valeurs
tableau = np.arange(1, 13)
tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
matrice_3x4 = tableau.reshape(3, 4)
matrice_3x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
matrice_4x3 = tableau.reshape(4, 3)
matrice_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
try:
    erreur = tableau.reshape(5, 3)
except ValueError as e:
    print(e)

cannot reshape array of size 12 into shape (5,3)


In [113]:
matrice_auto = tableau.reshape(3, -1)
matrice_auto
# reshape(3, -1) signifie 3lignes et trouve automatiquement le nombre de colonnes.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Exercice 1.10 — Transpose
Objectif : Comprendre la transposition de matrices. 

Instructions :

- Construisez une matrice 2D à partir de 3 colonnes numériques du dataset employés.
- Transposez-la avec .T.
- Vérifiez que la forme (shape) a bien été inversée.<br> 
**Difficulté*** : 🟡 Intermédiaire

In [116]:
# Sélection de 3 colonnes numériques
matrice = employes[
    [
        "Age",
        "Salaire_Mensuel_BIF",
        "Nombre_Absences"
    ]
].values
matrice.shape

(238, 3)

In [117]:
matrice_transposee = matrice.T
matrice_transposee.shape

(3, 238)

## Exercice 1.11 — Multiplication matricielle
Objectif : Manipuler le produit matriciel, base mathématique du Machine Learning. 

Instructions :

- Créez un vecteur de poids représentant l'importance de 3 critères (par exemple - - Evaluation_Performance, Anciennete_Entreprise, Nombre_Promotions).
- Calculez un "score composite" pour chaque employé à l'aide d'un produit matriciel (@ ou np.dot) entre la matrice des critères et le vecteur de poids.
- Identifiez les 5 employés ayant le score le plus élevé.<br> 
**Difficulté** : 🟡 Intermédiaire

In [118]:
# Sélection des critères
criteres = employes[
    [
        "Evaluation_Performance",
        "Anciennete_Entreprise",
        "Nombre_Promotions"
    ]
].values

print(criteres[:5])

[[ 3.  8.  0.]
 [ 5.  2.  0.]
 [ 2. 11.  2.]
 [ 5.  4.  1.]
 [ 3.  1.  1.]]


In [120]:
poids = np.array([
    0.5,
    0.3,
    0.2
])
scores = criteres @ poids
# scores = np.dot(criteres, poids)

print(scores[:10])

[3.9 3.1 4.7 3.9 2.  2.  5.  8.8 2.  0.5]


In [121]:
employes["Score_Composite"] = scores

# Employe avec le score le plus eleve
top_5 = employes.sort_values(
    by="Score_Composite",
    ascending=False
).head(5)
top_5

,ID_Employe,Age,Sexe,Departement,Annees_Experience,Niveau_Etudes,Salaire_Mensuel_BIF,Travail_A_Distance,Heures_Supplementaires,Heures_Formation,Anciennete_Entreprise,Nombre_Promotions,Evaluation_Performance,Equilibre_Vie_Travail,Satisfaction_Salaire,Nombre_Absences,Satisfait,Score_Composite
228,229,50.0,Homme,Logistique,32.0,Licence,5013803.0,Non,30.0,58.0,26.0,6.0,5.0,Bon,Très satisfait,3.0,Oui,11.5
147,148,49.0,Homme,Ressources Humaines,26.0,Licence,4632481.0,Non,25.0,100.0,26.0,4.0,3.0,Moyen,Insatisfait,15.0,Oui,10.1
229,230,49.0,Homme,Marketing,23.0,Licence,4190692.0,Non,6.0,73.0,22.0,4.0,5.0,Mauvais,Satisfait,9.0,Oui,9.9
414,415,58.0,Homme,Recherche et Développement,35.0,Licence,6000000.0,Oui,22.0,86.0,23.0,0.0,5.0,Bon,Insatisfait,18.0,Oui,9.4
300,301,49.0,Femme,Informatique,28.0,Licence,6000000.0,Non,15.0,77.0,20.0,3.0,5.0,Mauvais,Neutre,25.0,Oui,9.1


## Exercice 1.12 — Statistiques descriptives avec NumPy
Objectif : Calculer des indicateurs statistiques sans Pandas. 

Instructions :

- Calculez la moyenne, la médiane, l'écart-type, le minimum et le maximum de Salaire_Mensuel_BIF en utilisant uniquement des fonctions NumPy.
- Calculez le 25ᵉ et le 75ᵉ percentile de cette même colonne.
- Comparez vos résultats à ceux que vous obtiendrez plus tard avec DataFrame.describe().<br> 
**Difficulté** : 🟡 Intermédiaire

In [122]:
print("Moyenne :", np.mean(salaires))
print("Médiane :", np.median(salaires))
print("Écart-type :", np.std(salaires))
print("Minimum :", np.min(salaires))
print("Maximum :", np.max(salaires))

Moyenne : 2391203.567226891
Médiane : 1783310.0
Écart-type : 1721288.0187687017
Minimum : 300558.0
Maximum : 6000000.0


In [123]:
q25 = np.percentile(salaires, 25)
q75 = np.percentile(salaires, 75)

print("25e percentile :", q25)
print("75e percentile :", q75)

25e percentile : 956114.25
75e percentile : 3501730.0


In [124]:
employes["Salaire_Mensuel_BIF"].describe()

count    2.380000e+02
mean     2.398803e+06
std      1.722079e+06
min      3.005580e+05
25%      9.610732e+05
50%      1.787612e+06
75%      3.501730e+06
max      6.000000e+06
Name: Salaire_Mensuel_BIF, dtype: float64

## Exercice 1.13 — Le module random
Objectif : Générer des données aléatoires reproductibles. 

Instructions :

- Fixez une graine (seed) pour rendre vos résultats reproductibles.
- Générez un tableau simulant 100 âges aléatoires suivant une distribution proche de celle observée dans le dataset réel.
- Tirez aléatoirement, sans remise, les indices de 10 employés (utile pour créer un échantillon d'audit).<br> 
**Difficulté** : 🔴 Avancé

In [125]:
# Fixer la graine aléatoire
np.random.seed(42)

In [126]:
# Génération de 100 âges simulés
ages_simules = np.random.normal(
    loc=35,      # moyenne
    scale=8,     # écart-type
    size=100
)

print(ages_simules[:10])

[38.97371322 33.89388559 40.1815083  47.18423885 33.126773   33.12690434
 47.63370252 41.13947783 31.24420491 39.34048035]


In [127]:
ages_simules = np.round(ages_simules)

# Limiter entre 20 et 60 ans
ages_simules = np.clip(
    ages_simules,
    20,
    60
)

print(ages_simules[:10])

[39. 34. 40. 47. 33. 33. 48. 41. 31. 39.]


In [128]:
nombre_employes = len(employes)

indices_audit = np.random.choice(
    nombre_employes,
    size=10,
    replace=False
)

print(indices_audit)

[199  55 172  33 234  54 107 108  91 205]


## Exercice 1.14 — Notions d'algèbre linéaire (np.linalg)
Objectif : Découvrir les outils d'algèbre linéaire utilisés en Machine Learning. 

Instructions :

- Construisez une petite matrice carrée (2×2 ou 3×3) à partir de données numériques de votre choix.
- Calculez son déterminant et, si possible, son inverse avec np.linalg.
- Recherchez à quoi sert np.linalg dans le contexte de la régression linéaire (ce lien sera revu en Partie 5).<br> 
**Difficulté** : 🔴 Avancé

In [129]:
# Création d'une matrice carrée 3x3
A = np.array([
    [4, 2, 1],
    [3, 5, 2],
    [1, 2, 6]
])

print(A)

[[4 2 1]
 [3 5 2]
 [1 2 6]]


In [130]:
det_A = np.linalg.det(A)
print("Déterminant :", det_A)

Déterminant : 72.99999999999999


In [134]:
A_inverse = np.linalg.inv(A)
print("Inverse de A :\n", A_inverse)

Inverse de A :
 [[ 0.35616438 -0.1369863  -0.01369863]
 [-0.21917808  0.31506849 -0.06849315]
 [ 0.01369863 -0.08219178  0.19178082]]


**np.linalg** est une bibliothèque fondamentale pour la manipulation matricielle, et elle intervient directement dans les fondements mathématiques de plusieurs algorithmes de **Machine Learning**, notamment la **régression linéaire**, les **moindres carrés** et certaines méthodes d'optimisation.

## Exercice 1.15 — Notions de probabilité utiles pour le Machine Learning
Objectif : Relier NumPy à des concepts probabilistes de base. 

Instructions :

- Calculez, uniquement avec NumPy (booléens + mean()), la proportion d'employés satisfaits (Satisfait == "Oui") : cette proportion est une estimation d'une probabilité.
- Standardisez (z-score) la colonne Age et expliquez pourquoi cette transformation est utile avant d'entraîner un modèle.
- Discutez en une ou deux phrases du lien entre fréquence observée et probabilité en Machine Learning.<br> 
**Difficulté** : 🔴 Avancé

In [136]:
# Conversion de la colonne Satisfait en tableau NumPy
satisfaits = employes["Satisfait"].values

# Calcul de la proportion de Oui
proportion_satisfaits = np.mean(satisfaits == "Oui")

print("Proportion d'employés satisfaits :", proportion_satisfaits)

Proportion d'employés satisfaits : 0.6008403361344538


In [138]:
# Extraction de Age en tableau NumPy
ages = employes["Age"].values

# Calcul de la moyenne et de l'écart-type
moyenne_age = np.mean(ages)
ecart_type_age = np.std(ages)

# Standardisation
age_standardise = (
    ages - moyenne_age
) / ecart_type_age

print(age_standardise[:10])
print("Moyenne: ", np.mean(age_standardise))     
print("Ecart-type: ", np.std(age_standardise))

[ 1.51973913 -1.06441282  1.51973913  0.18598329 -0.8143336  -0.8143336
 -1.56457126  0.26934303 -1.56457126  0.26934303]
Moyenne
 8.863124986503351e-17
Ecart-type
 1.0


La standardisation est utile car les variables peuvent avoir des échelles différentes.

Par exemple :

Age : entre 20 et 60 ;
Salaire_Mensuel_BIF : centaines de milliers de BIF ;
Nombre_Absences : quelques unités.

Sans standardisation, certaines variables avec de grandes valeurs peuvent avoir une influence disproportionnée sur le modèle, notamment pour :

la régression linéaire ;
la régression logistique ;
les réseaux de neurones ;
les algorithmes utilisant les distances (KNN, clustering).

La transformation en z-score place les variables sur une échelle comparable.

In [139]:
"""
En Machine Learning, une probabilité est souvent estimée à partir des 
fréquences observées dans les données d'entraînement. 
Plus le nombre d'observations augmente, plus la fréquence empirique se rapproche 
généralement de la vraie probabilité du phénomène étudié.
"""

"\nEn Machine Learning, une probabilité est souvent estimée à partir des \nfréquences observées dans les données d'entraînement. \nPlus le nombre d'observations augmente, plus la fréquence empirique se rapproche \ngénéralement de la vraie probabilité du phénomène étudié.\n"